import { MovieModel } from '../models/movie/movie.model';

export const MOVIE_LIST_MOCKDATA: MovieModel[] = [
    {
        id: 1,
        name: 'Innocent Blood',
        directorName: 'Cisec',
        directorEmail: 'scisec0@dedecms.com',
        gener: 0,
        startDate: '05/11/1943',
        endDate: '06/24/1950',
        type: 0,
        country: 'China',
        score: 1,
    },
    {
        id: 2,
        name: 'Fans',
        directorName: 'McLucas',
        directorEmail: 'rmclucas1@so-net.ne.jp',
        gener: 3,
        startDate: '08/22/2007',
        endDate: '03/24/1998',
        type: 1,
        country: 'Sweden',
        score: 13,
    },
    {
        id: 3,
        name: 'City Under Siege (Chun sing gai bei)',
        directorName: 'Fillan',
        directorEmail: 'efillan2@zimbio.com',
        gener: 0,
        startDate: '12/18/1979',
        endDate: '02/14/1921',
        type: 0,
        country: 'Kazakhstan',
        score: 20,
    },
    {
        id: 4,
        name: 'People Under the Stairs, The',
        directorName: 'Stickford',
        directorEmail: 'bstickford3@1688.com',
        gener: 2,
        startDate: '08/28/1993',
        endDate: '12/10/1964',
        type: 1,
        country: 'Czech Republic',
        score: 9,
    },
    {
        id: 5,
        name: '35 Shots of Rum (35 rhums)',
        directorName: 'Blunsden',
        directorEmail: 'vblunsden4@hud.gov',
        gener: 0,
        startDate: '09/17/2006',
        endDate: '03/12/1986',
        type: 0,
        country: 'Cameroon',
        score: 1,
    },
    {
        id: 6,
        name: 'Mitt',
        directorName: 'Gaythorpe',
        directorEmail: 'ngaythorpe5@nhs.uk',
        gener: 1,
        startDate: '10/11/1941',
        endDate: '09/26/1924',
        type: 1,
        country: 'Portugal',
        score: 7,
    },
    {
        id: 7,
        name: 'Speed & Angels',
        directorName: 'Shelley',
        directorEmail: 'rshelley6@house.gov',
        gener: 1,
        startDate: '07/31/1924',
        endDate: '02/16/2004',
        type: 0,
        country: 'Nicaragua',
        score: 6,
    },
    {
        id: 8,
        name: 'Lightning Bolt: The Power of Salad',
        directorName: 'Suggitt',
        directorEmail: 'lsuggitt7@forbes.com',
        gener: 3,
        startDate: '08/13/1950',
        endDate: '04/30/1929',
        type: 0,
        country: 'Peru',
        score: 7,
    },
    {
        id: 9,
        name: 'Pinochet Case, The (Cas Pinochet, Le)',
        directorName: 'Korneev',
        directorEmail: 'skorneev8@shop-pro.jp',
        gener: 2,
        startDate: '01/12/1969',
        endDate: '05/17/1904',
        type: 0,
        country: 'China',
        score: 11,
    },
    {
        id: 10,
        name: 'Good Wife, The',
        directorName: 'Ivachyov',
        directorEmail: 'mivachyov9@hp.com',
        gener: 2,
        startDate: '08/14/2011',
        endDate: '06/13/2011',
        type: 1,
        country: 'Greece',
        score: 11,
    },
    {
        id: 11,
        name: 'Messenger: The Story of Joan of Arc, The',
        directorName: 'MacKilroe',
        directorEmail: 'rmackilroea@feedburner.com',
        gener: 1,
        startDate: '11/07/1942',
        endDate: '06/22/1986',
        type: 0,
        country: 'Argentina',
        score: 7,
    },
    {
        id: 12,
        name: 'Everybody Street',
        directorName: 'Charlick',
        directorEmail: 'fcharlickb@go.com',
        gener: 0,
        startDate: '01/12/1991',
        endDate: '11/19/1977',
        type: 0,
        country: 'Argentina',
        score: 2,
    },
    {
        id: 13,
        name: 'Live Wire',
        directorName: 'Scrancher',
        directorEmail: 'ascrancherc@usgs.gov',
        gener: 1,
        startDate: '09/05/1947',
        endDate: '12/16/1924',
        type: 1,
        country: 'China',
        score: 14,
    },
    {
        id: 14,
        name: 'Deserter (Dezertir)',
        directorName: 'Harcus',
        directorEmail: 'charcusd@webnode.com',
        gener: 3,
        startDate: '10/25/1985',
        endDate: '09/27/1975',
        type: 0,
        country: 'Poland',
        score: 10,
    },
    {
        id: 15,
        name: 'Thirst',
        directorName: 'Berks',
        directorEmail: 'kberkse@posterous.com',
        gener: 2,
        startDate: '02/09/1959',
        endDate: '08/15/1955',
        type: 1,
        country: 'China',
        score: 14,
    },
    {
        id: 16,
        name: 'Basic Instinct 2',
        directorName: 'Pennuzzi',
        directorEmail: 'mpennuzzif@webmd.com',
        gener: 2,
        startDate: '04/12/1986',
        endDate: '10/05/2010',
        type: 1,
        country: 'China',
        score: 7,
    },
    {
        id: 17,
        name: 'In Their Skin',
        directorName: 'Boddymead',
        directorEmail: 'hboddymeadg@ycombinator.com',
        gener: 1,
        startDate: '05/08/1947',
        endDate: '01/04/2008',
        type: 1,
        country: 'Czech Republic',
        score: 12,
    },
    {
        id: 18,
        name: 'Jane Eyre',
        directorName: 'McQuaide',
        directorEmail: 'dmcquaideh@pcworld.com',
        gener: 3,
        startDate: '11/16/2021',
        endDate: '08/28/1915',
        type: 0,
        country: 'Peru',
        score: 5,
    },
    {
        id: 19,
        name: 'Mandingo',
        directorName: 'Grabb',
        directorEmail: 'ngrabbi@sciencedaily.com',
        gener: 3,
        startDate: '05/10/1955',
        endDate: '06/17/1915',
        type: 0,
        country: 'Vietnam',
        score: 9,
    },
    {
        id: 20,
        name: 'Cosmic Journey',
        directorName: 'Lennox',
        directorEmail: 'klennoxj@nature.com',
        gener: 2,
        startDate: '04/01/1956',
        endDate: '12/21/1962',
        type: 0,
        country: 'Brazil',
        score: 5,
    },
    {
        id: 21,
        name: 'Hair Show',
        directorName: 'Lambert-Ciorwyn',
        directorEmail: 'slambertciorwynk@ezinearticles.com',
        gener: 3,
        startDate: '09/15/1916',
        endDate: '11/27/1967',
        type: 0,
        country: 'France',
        score: 15,
    },
    {
        id: 22,
        name: 'Sundome',
        directorName: 'Albrook',
        directorEmail: 'aalbrookl@kickstarter.com',
        gener: 4,
        startDate: '06/27/1908',
        endDate: '08/15/1981',
        type: 1,
        country: 'France',
        score: 4,
    },
    {
        id: 23,
        name: 'Runaway Jury',
        directorName: 'Bazell',
        directorEmail: 'dbazellm@dion.ne.jp',
        gener: 3,
        startDate: '12/10/1989',
        endDate: '04/04/1990',
        type: 1,
        country: 'Russia',
        score: 9,
    },
    {
        id: 24,
        name: 'Zipper',
        directorName: 'Bridgeman',
        directorEmail: 'wbridgemann@privacy.gov.au',
        gener: 2,
        startDate: '08/01/1939',
        endDate: '11/22/1968',
        type: 0,
        country: 'Czech Republic',
        score: 5,
    },
    {
        id: 25,
        name: 'Adios Carmen',
        directorName: 'Jaqueminet',
        directorEmail: 'ljaquemineto@123-reg.co.uk',
        gener: 3,
        startDate: '11/15/2009',
        endDate: '04/30/1961',
        type: 1,
        country: 'Poland',
        score: 1,
    },
    {
        id: 26,
        name: 'Under Fire',
        directorName: 'Abrahamsson',
        directorEmail: 'sabrahamssonp@ask.com',
        gener: 4,
        startDate: '08/26/1984',
        endDate: '01/09/1997',
        type: 1,
        country: 'China',
        score: 17,
    },
    {
        id: 27,
        name: 'Black Swan',
        directorName: 'Bernhard',
        directorEmail: 'rbernhardq@geocities.com',
        gener: 4,
        startDate: '11/06/1908',
        endDate: '02/10/1936',
        type: 0,
        country: 'Canada',
        score: 18,
    },
    {
        id: 28,
        name: 'Black Friday',
        directorName: 'Castagneri',
        directorEmail: 'lcastagnerir@acquirethisname.com',
        gener: 2,
        startDate: '07/29/1927',
        endDate: '01/04/1993',
        type: 1,
        country: 'Indonesia',
        score: 4,
    },
    {
        id: 29,
        name: 'I Wish (Kiseki)',
        directorName: 'Worthington',
        directorEmail: 'gworthingtons@twitpic.com',
        gener: 1,
        startDate: '07/22/1923',
        endDate: '12/13/1962',
        type: 1,
        country: 'Indonesia',
        score: 14,
    },
    {
        id: 30,
        name: 'Protector, The',
        directorName: 'Steptowe',
        directorEmail: 'rsteptowet@pcworld.com',
        gener: 1,
        startDate: '02/16/1917',
        endDate: '09/12/1906',
        type: 1,
        country: 'Latvia',
        score: 4,
    },
    {
        id: 31,
        name: 'Samson & Sally',
        directorName: 'Dongall',
        directorEmail: 'ndongallu@china.com.cn',
        gener: 4,
        startDate: '05/10/2015',
        endDate: '04/01/2013',
        type: 0,
        country: 'Nigeria',
        score: 20,
    },
    {
        id: 32,
        name: 'Serenity',
        directorName: 'Masterman',
        directorEmail: 'smastermanv@shutterfly.com',
        gener: 2,
        startDate: '07/12/1938',
        endDate: '08/14/1932',
        type: 0,
        country: 'Russia',
        score: 7,
    },
    {
        id: 33,
        name: '7 Days in Havana',
        directorName: 'Karolovsky',
        directorEmail: 'bkarolovskyw@timesonline.co.uk',
        gener: 1,
        startDate: '03/14/1973',
        endDate: '01/18/2022',
        type: 0,
        country: 'Brazil',
        score: 20,
    },
    {
        id: 34,
        name: 'Sunday in Kigali, A (Un dimanche à Kigali)',
        directorName: 'Christaeas',
        directorEmail: 'vchristaeasx@goodreads.com',
        gener: 3,
        startDate: '12/04/2012',
        endDate: '09/15/2015',
        type: 1,
        country: 'China',
        score: 19,
    },
    {
        id: 35,
        name: 'Howards End',
        directorName: 'Watsam',
        directorEmail: 'vwatsamy@xrea.com',
        gener: 1,
        startDate: '02/18/1916',
        endDate: '07/09/1995',
        type: 1,
        country: 'Philippines',
        score: 19,
    },
    {
        id: 36,
        name: 'Lost City, The',
        directorName: 'Flamank',
        directorEmail: 'nflamankz@independent.co.uk',
        gener: 2,
        startDate: '02/12/1954',
        endDate: '07/15/1993',
        type: 1,
        country: 'Tanzania',
        score: 8,
    },
    {
        id: 37,
        name: 'Prodigal Son, The (Bai ga jai)',
        directorName: 'Faltin',
        directorEmail: 'kfaltin10@reverbnation.com',
        gener: 3,
        startDate: '06/16/1976',
        endDate: '01/29/1946',
        type: 1,
        country: 'Indonesia',
        score: 1,
    },
    {
        id: 38,
        name: 'Last Warrior, The (Last Patrol, The)',
        directorName: 'Strettell',
        directorEmail: 'ustrettell11@dedecms.com',
        gener: 4,
        startDate: '11/01/1931',
        endDate: '03/28/1962',
        type: 0,
        country: 'Philippines',
        score: 19,
    },
    {
        id: 39,
        name: 'Waking Life',
        directorName: 'Callaghan',
        directorEmail: 'dcallaghan12@angelfire.com',
        gener: 2,
        startDate: '03/27/1951',
        endDate: '08/14/2012',
        type: 0,
        country: 'Indonesia',
        score: 17,
    },
    {
        id: 40,
        name: 'River of No Return',
        directorName: 'Schrieves',
        directorEmail: 'aschrieves13@paginegialle.it',
        gener: 3,
        startDate: '01/24/1994',
        endDate: '06/30/1989',
        type: 0,
        country: 'China',
        score: 13,
    },
    {
        id: 41,
        name: 'Father Sergius (Otets Sergiy)',
        directorName: 'Dossettor',
        directorEmail: 'ndossettor14@bloglines.com',
        gener: 0,
        startDate: '04/02/1952',
        endDate: '03/11/1997',
        type: 0,
        country: 'Indonesia',
        score: 15,
    },
    {
        id: 42,
        name: 'Pusher',
        directorName: 'Gehricke',
        directorEmail: 'fgehricke15@flickr.com',
        gener: 2,
        startDate: '06/19/1901',
        endDate: '03/29/1931',
        type: 1,
        country: 'Japan',
        score: 20,
    },
    {
        id: 43,
        name: 'Nocturno 29',
        directorName: 'Lukianov',
        directorEmail: 'rlukianov16@arizona.edu',
        gener: 4,
        startDate: '09/30/1936',
        endDate: '12/22/1975',
        type: 1,
        country: 'Canada',
        score: 14,
    },
    {
        id: 44,
        name: 'At Long Last Love',
        directorName: 'Biggadike',
        directorEmail: 'dbiggadike17@whitehouse.gov',
        gener: 0,
        startDate: '03/14/1918',
        endDate: '05/13/1962',
        type: 1,
        country: 'Brazil',
        score: 5,
    },
    {
        id: 45,
        name: 'Burial Ground (a.k.a. Zombie Horror) (a.k.a. Zombie 3) (Notti del Terrore, Le)',
        directorName: 'Le Pruvost',
        directorEmail: 'slepruvost18@scribd.com',
        gener: 3,
        startDate: '06/17/1999',
        endDate: '09/13/1903',
        type: 0,
        country: 'Argentina',
        score: 19,
    },
    {
        id: 46,
        name: "Cocaine Cowboys II: Hustlin' With the Godmother",
        directorName: 'Dedmam',
        directorEmail: 'tdedmam19@comsenz.com',
        gener: 2,
        startDate: '07/16/2007',
        endDate: '02/24/2019',
        type: 0,
        country: 'China',
        score: 12,
    },
    {
        id: 47,
        name: 'Don',
        directorName: 'Gozney',
        directorEmail: 'egozney1a@deliciousdays.com',
        gener: 4,
        startDate: '01/12/1960',
        endDate: '12/05/1902',
        type: 0,
        country: 'China',
        score: 16,
    },
    {
        id: 48,
        name: 'Les Lyonnais',
        directorName: 'McGuane',
        directorEmail: 'jmcguane1b@nps.gov',
        gener: 4,
        startDate: '12/10/2018',
        endDate: '08/30/1954',
        type: 1,
        country: 'Finland',
        score: 13,
    },
    {
        id: 49,
        name: 'Eversmile, New Jersey',
        directorName: 'Mullaly',
        directorEmail: 'lmullaly1c@people.com.cn',
        gener: 0,
        startDate: '10/03/2017',
        endDate: '04/13/1908',
        type: 1,
        country: 'Ukraine',
        score: 1,
    },
    {
        id: 50,
        name: 'From Justin to Kelly',
        directorName: 'Benazet',
        directorEmail: 'hbenazet1d@sciencedaily.com',
        gener: 2,
        startDate: '09/11/1955',
        endDate: '03/07/1903',
        type: 1,
        country: 'Russia',
        score: 12,
    },
];
